from __future__ import annotations

from app.orchestrator.execution_contracts import (
    ExecutionOutcome,
    FallbackPolicy,
    SpecialistContract,
)


SPECIALIST_CONTRACTS: dict[str, SpecialistContract] = {
    "product_assistant": SpecialistContract(
        action="product_assistant",
        endpoint="/product/assistant/ask",
        owner="routers/hybrid_api.py:product_assistant_ask",
        required_fields=("vraag",),
        accepted_input_fields=(
            "vraag",
            "q",
            "family_name",
            "family_code",
            "belt_width_mm",
            "choice_type",
            "component_group",
            "mode",
            "limit",
        ),
        planner_fields=("vraag", "mode"),
        research_fields=(
            "vraag",
            "family_code",
            "belt_width_mm",
            "choice_type",
            "component_group",
            "mode",
            "limit",
        ),
        direct_planner="YES",
        legacy_fallback_allowed=True,
        fallback_policy=FallbackPolicy.UNRESOLVED,
        status_contract_state="STATIC_OBSERVED",
        status_map={
            "ok": ExecutionOutcome.SUCCESS,
        },
    ),
    "analysis_assistant": SpecialistContract(
        action="analysis_assistant",
        endpoint="/analysis/assistant/ask",
        owner="routers/analysis_api_v10.py:analysis_assistant_ask",
        required_fields=("vraag",),
        accepted_input_fields=(
            "vraag",
            "lijn_code",
            "date_from",
            "date_to",
            "band_code",
            "scraper_type",
            "zijde",
            "scope_code",
            "scope_type",
            "area_code",
            "installation_code",
            "limit",
        ),
        planner_fields=("vraag", "mode"),
        research_fields=(
            "vraag",
            "lijn_code",
            "band_code",
            "scraper_type",
            "zijde",
            "date_from",
            "date_to",
            "mode",
            "limit",
            "scope_code",
            "scope_type",
            "area_code",
            "installation_code",
        ),
        direct_planner="YES",
        legacy_fallback_allowed=True,
        fallback_policy=FallbackPolicy.UNRESOLVED,
        status_contract_state="STATIC_OBSERVED",
        status_map={
            "resolved": ExecutionOutcome.SUCCESS,
            "clarification_required": ExecutionOutcome.CLARIFICATION_REQUIRED,
            "ambiguous": ExecutionOutcome.AMBIGUOUS,
            "context_conflict": ExecutionOutcome.CONTEXT_CONFLICT,
            "not_found": ExecutionOutcome.NOT_FOUND,
            "unavailable": ExecutionOutcome.UNAVAILABLE,
        },
    ),
    "technical_assistant": SpecialistContract(
        action="technical_assistant",
        endpoint="/technical/assistant/ask",
        owner="routers/hybrid_api.py:technical_assistant_ask",
        required_fields=("vraag",),
        accepted_input_fields=(
            "vraag",
            "q",
            "topic_group",
            "source_code",
            "item_type",
            "use_rag",
            "limit",
        ),
        planner_fields=("vraag", "use_rag"),
        research_fields=(
            "vraag",
            "topic_group",
            "source_code",
            "item_type",
            "use_rag",
            "limit",
        ),
        direct_planner="YES",
        legacy_fallback_allowed=True,
        fallback_policy=FallbackPolicy.UNRESOLVED,
        status_contract_state="STATIC_OBSERVED",
        status_map={
            "ok": ExecutionOutcome.SUCCESS,
            "redirect": ExecutionOutcome.REDIRECT,
        },
    ),
    "rfq_assistant": SpecialistContract(
        action="rfq_assistant",
        endpoint="/rfq/assistant/ask",
        owner="routers/hybrid_api.py:rfq_assistant_ask",
        required_fields=("vraag",),
        accepted_input_fields=(
            "vraag",
            "q",
            "rfq_id",
            "position_id",
            "product_type",
            "bearing_type",
            "rubber_material",
            "language",
            "mode",
            "limit",
        ),
        planner_fields=(),
        research_fields=(
            "vraag",
            "rfq_id",
            "position_id",
            "product_type",
            "bearing_type",
            "rubber_material",
            "language",
            "mode",
            "limit",
        ),
        direct_planner="NO_UNRESOLVED_INTENT",
        legacy_fallback_allowed=None,
        fallback_policy=FallbackPolicy.UNRESOLVED,
        status_contract_state="STATIC_PARTIAL_ERROR_ONLY",
        status_map={
            "error": ExecutionOutcome.ERROR,
            "<other>": ExecutionOutcome.UNKNOWN,
        },
    ),
    "org_assistant": SpecialistContract(
        action="org_assistant",
        endpoint="/org/assistant/ask",
        owner="routers/hybrid_api.py:org_assistant_ask",
        required_fields=("vraag",),
        accepted_input_fields=(
            "vraag",
            "firma",
            "locatie",
            "afdeling",
            "mode",
        ),
        planner_fields=("vraag", "firma", "mode"),
        research_fields=(
            "vraag",
            "firma",
            "locatie",
            "afdeling",
            "mode",
        ),
        direct_planner="YES",
        legacy_fallback_allowed=True,
        fallback_policy=FallbackPolicy.UNRESOLVED,
        status_contract_state="DELEGATED_NO_STATIC_STATUS",
        status_map={
            "<unknown>": ExecutionOutcome.UNKNOWN,
        },
    ),
    "diagnostics_assistant": SpecialistContract(
        action="diagnostics_assistant",
        endpoint="/diagnostics/assistant/ask",
        owner="routers/hybrid_api.py:diagnostics_assistant_ask",
        required_fields=("vraag",),
        accepted_input_fields=(
            "vraag",
            "domain",
            "mode",
            "objects",
            "inspection_key",
            "lijn_code",
            "band_code",
            "source_file_contains",
            "sheet",
            "diagnosis_code",
            "filters",
            "depth",
            "limit",
        ),
        planner_fields=(
            "vraag",
            "domain",
            "mode",
            "depth",
            "limit",
        ),
        research_fields=(
            "vraag",
            "domain",
            "mode",
            "inspection_key",
            "lijn_code",
            "band_code",
            "source_file_contains",
            "sheet",
            "diagnosis_code",
            "depth",
            "limit",
        ),
        direct_planner="YES",
        legacy_fallback_allowed=True,
        fallback_policy=FallbackPolicy.UNRESOLVED,
        status_contract_state="DELEGATED_DYNAMIC_STATUS",
        status_map={
            "<unknown>": ExecutionOutcome.UNKNOWN,
        },
    ),
}


EXPECTED_SPECIALIST_ACTIONS = frozenset(
    {
        "product_assistant",
        "analysis_assistant",
        "technical_assistant",
        "rfq_assistant",
        "org_assistant",
        "diagnostics_assistant",
    }
)


def get_specialist_contract(
    action: str,
) -> SpecialistContract | None:
    return SPECIALIST_CONTRACTS.get(action)